version: '3.8'

services:
  jenkins-master:
    image: tjleite87/jenkins:1.0.1
    container_name: jenkins-master
    restart: on-failure
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3

  jenkins-slave:
    build:
      context: ./slave
    container_name: jenkins-slave
    hostname: jenkins-slave
    restart: unless-stopped
    depends_on:
      jenkins-master:
        condition: service_healthy
    ports:
      - "2222:22"
    environment:
      - AUTO_REGISTER_AGENT=true
      - JENKINS_MASTER_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=jenkins-slave
      - JENKINS_AGENT_WORKDIR=/home/jenkins/slave/workspace
      - JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
    volumes:
      - type: bind
        source: ./jenkins-slave-data
        target: /home/jenkins/slave
      - type: bind
        source: ./jenkins-slave-ssh
        target: /etc/ssh/keys
    networks:
      - jenkins

volumes:
  jenkins-data:
  jenkins-docker-certs:
networks:
  jenkins:
    driver: bridge